### ISSUE TITLE
Sugestão de alteração do texto de apresentação do manifesto na home

### ISSUE THREAD

**Issue by victormsimao** [go-fair-agro/go-fair-agro.github.io#6]
Alterar o texto de apresentação do manifesto, pois está algo confuso:
Texto atual:

O Escritório de Apoio de Coordenação GO-FAIR Brasil é um dos escritórios regionais de apoio e coordenação da rede GO-FAIR e tem a responsabilidade de difundir, apoiar e coordenar as atividades relacionadas à adoção da estratégia de implementação dos princípios FAIR definida pela iniciativa GO-FAIR em todo o território brasileiro.

Sugestão 1
O Escritório de Apoio de Coordenação GO-FAIR Brasil é um dos escritórios regionais da rede GO-FAIR e tem a responsabilidade de difundir, apoiar e coordenar as atividades preconizadas pela Rede para a adoção e implementação dos princípios FAIR em todo o território brasileiro.

Sugestão 2
O Escritório de Apoio de Coordenação GO-FAIR Brasil é um dos escritórios regionais da rede GO-FAIR e tem a responsabilidade de difundir, apoiar e coordenar as atividades relacionadas à adoção da estratégia de implementação dos princípios FAIR definida pela iniciativa GO-FAIR em todo o território brasileiro.

**Comment by prbbertin** [comment]
Na seção 'Lançamento', sugiro incluir o ano: 
"Aconteceu no dia 12 de abril [de 2022]..."
