### ISSUE TITLE
Seção 'Participantes'

### ISSUE THREAD

**Issue by prbbertin** [go-fair-agro/go-fair-agro.github.io#7]
Não sei se é isto o que se pretende com o item 'Participantes', do menu superior do site, mas senti falta de indicações de contatos pessoais (em vez de apenas institucionais). No momento, o texto remete o leitor apenas à informação de que a Rede GO-FAIR Agro Brasil é coordenada pela Embrapa, em gestão colegiada com UFRRJ, USP, Unipampa e UFRJ, mas essas instituições são um mundo. Quem são os pontos-focais? Ou de repente poderíamos divulgar uma conta de e-mail do GO FAIR Agro?

**Comment by mitelles** [comment]
Para mim, nem a sessão participantes levou ao mesmo conteúdo de publicações. O mesmo aconteceu para Contato.
